name: Python application test with Github Actions

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out project
      uses: actions/checkout@v2
      
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: |
        make install
        
    - name: Lint with pylint
      run: |
        make lint
        
    - name: Configure-AWS-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.WEEKLYSTOCK_DB_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.WEEKLYSTOCK_DB_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Test with pytest
      run: |
        make test
      
    - name: Record successful build
      run: |
        echo Build completed on `date`
